services:
  postgres:
    image: postgres:16.6
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/hummingbird
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=spruser
      - POSTGRES_DB=swiftpackageregistry

volumes:
  db:
    driver: local
